CREATE SCHEMA moe_sounds AUTHORIZATION DBA;

CREATE TABLE moe_sounds.user (
  user_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1  INCREMENT BY 1),
  nickname varchar(45) NOT NULL,
  google_id varchar(21) NOT NULL,
  PRIMARY KEY (user_id)
);

CREATE TABLE moe_sounds.page (
  page_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1  INCREMENT BY 1),
  page_name varchar(45) NOT NULL,
  css LONGVARCHAR NOT NULL,
  click_count int DEFAULT 0,
  PRIMARY KEY (page_id)
  
);

CREATE TABLE moe_sounds.page_media (
  page_media_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1  INCREMENT BY 1),
  page_id int NOT NULL,
  carousel_image_small BLOB,
  carousel_image_big BLOB,
  background_page BLOB,
  background_inner BLOB,
  sound_file BLOB,
  PRIMARY KEY (page_media_id),
  FOREIGN KEY (page_id) REFERENCES moe_sounds.page(page_id)
);
