CREATE SCHEMA moe_sounds AUTHORIZATION DBA;

CREATE TABLE moe_sounds.user (
  user_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1  INCREMENT BY 1),
  nickname varchar(45) NOT NULL,
  user_role varchar(45) NOT NULL,
  PRIMARY KEY (user_id)
);

CREATE TABLE moe_sounds.user_api_identity (
  user_api_identity_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1  INCREMENT BY 1),
  user_id int NOT NULL,
  api_type varchar(45) NOT NULL,
  api_user_id varchar(45) NOT NULL,
  PRIMARY KEY (user_api_identity_id),
  FOREIGN KEY (user_id) REFERENCES moe_sounds.user(user_id)
);

CREATE TABLE moe_sounds.page (
  page_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1  INCREMENT BY 1),
  page_name varchar(45) NOT NULL,
  css LONGVARCHAR NOT NULL,
  click_count int DEFAULT 0,
  PRIMARY KEY (page_id)
);

CREATE TABLE moe_sounds.media (
  media_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1  INCREMENT BY 1),
  page_id int NOT NULL,
  media_type varchar(45) NOT NULL,
  file_name varchar(255) NOT NULL,
  file_type varchar(45) NOT NULL,
  file_data BLOB NOT NULL,
  file_size int NOT NULL,
  PRIMARY KEY (media_id),
  FOREIGN KEY (page_id) REFERENCES moe_sounds.page(page_id)
);
